"""empty message

Revision ID: 98188e53f2a7
Revises: 18f939fdf923
Create Date: 2022-07-14 14:48:18.920703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98188e53f2a7'
down_revision = '18f939fdf923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_name', sa.String(), nullable=True),
    sa.Column('frame_last_name', sa.String(), nullable=True),
    sa.Column('frame_password', sa.String(), nullable=True),
    sa.Column('frame_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('job_frames', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_frames'], ['frames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('frames')
    # ### end Alembic commands ###
